### ISSUE TITLE
psxact-20160216 APPCRASH 

### ISSUE THREAD

**Issue by Ramon-Zarat** [beannaich/psxact#7] opened 2016-02-18 06:51 UTC
Hi.

My system spec: 

Intel 2500K
16GB RAM
Nvidia GTX 660
Win 7 64 ultimate

------------------------------------------------------
psxact.exe instantly crash with this error: 

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	psxact.exe
  Application Version:	0.0.0.0
  Application Timestamp:	56c31b6e
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.10240.16390
  Fault Module Timestamp:	55a5b718
  Exception Code:	40000015
  Exception Offset:	0000000000065a5f
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	306a
  Additional Information 2:	306a2c1f180abc750886cac6f861b3fd
  Additional Information 3:	7cc1
  Additional Information 4:	7cc114d54940ca1f93d9c33344db935d

**Comment by beannaich** [comment] 2016-02-18 15:19
Hello,

Thank you for your interest in my project! Unfortunately, the emulator is not stable yet, and this is expected behavior with the current builds. When the emulator stabilizes, reports like these will have much more significance.

I'm closing this as `wontfix` because this will iron itself out as the emulator matures.

**Closed by beannaich** 2016-02-18 15:19 UTC
Labels: wontfix
